openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacnts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Contacnts UI
tags:
  - name: Contacts
    description: Operation with contacts
servers:
  - url: http://127.0.0.1:5010
  - url: https://contacts-t4m3.onrender.com

paths:
  /contacts:
    get:
      $ref: '../swagger/paths/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
    put:
      $ref: '../swagger/paths/contacts/{id}/put.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
